routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();
Route::middleware('auth')->group(function () {
    // Home
    Route::get('/', 'HomeController@index')->name('home');
    // Users
    Route::namespace('User')->group(function () {
        Route::get('psw', 'PswController@edit')->name('psw.edit');
        Route::put('psw', 'PswController@update')->name('psw.update');
        Route::middleware('admin')->group(function (){
            Route::resource('staff', 'StaffController')->except(['show']);
            Route::patch('staff/{staff}/restore', 'StaffController@restore')->name('staff.restore');
        });
    });
});

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Staff extends Model
{
    use SoftDeletes;

    protected $fillable = ["last_name", "first_name", "mobile", "cin", "category_id"];

    public function getFullNameAttribute()
    {
        return $this->last_name . ' ' . $this->first_name;
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->hasOne(User::class);
    }

    public function driven_trucks()
    {
        return $this->hasMany(Driver::class);
    }

    public function assisted_truck()
    {
        return $this->hasMany(Assistant::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'name', 'password', 'staff_id'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getIsAdminAttribute()
    {
        return $this->staff->category->category === 'admin';
    }

    public function staff()
    {
        return $this->belongsTo(Staff::class);
    }

    public function created_trucks()
    {
        return $this->hasMany(Truck::class,'creator_id');
    }

    public function created_charge_trucks()
    {
        return $this->hasMany(ChargeTruck::class,'creator_id');
    }

    public function created_partners()
    {
        return $this->hasMany(Partner::class,'creator_id');
    }

    public function created_trades()
    {
        return $this->hasMany(Trade::class,'creator_id');
    }

}

resources/views/layouts/_flash.blade.php
<div class="container">
    @if(session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if(session('danger'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ session('danger') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if(session('warning'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ session('warning') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
</div>

resources/views/layouts/_navbar.blade.php
<!-- header --->
<header class="admin-header">
    <div class="left-part">
        <a href="#" class="logo">
            <span class="logo-mini"></span>
            <span class="logo-lg"><b>Gaz </b> Control Panel </span>
        </a>
    </div>
    <div class="right-part">
        <a href="#" class="float-left to_small_sidebar" id="to_small_sidebar" data-toggle="push-menu" role="button">
            <i class="fa fa-bars" aria-hidden="true"></i>
        </a>

        <div class="dropdown float-right">
            <a role="button" class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <img src="{{ asset('images/logo-gaz.png') }}"
                     style="width:25px;border-radius:50%;margin-left: 5px;">
                {{ auth()->user()->staff->full_name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <a class="dropdown-item" href="{{ route('psw.edit') }}">mot de passe</a>
                <div class="dropdown-divider"></div>
                <a href="#"
                   onclick="event.preventDefault();
               document.getElementById('logout-form').submit();"
                   class="dropdown-item btn3 flex-c-m size13 txt11 trans-0-4 m-l-r-auto">
                    Se déconnecter
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
        <div class="dateete">
            @php setlocale(LC_TIME, "fr");@endphp
            {{  Carbon\Carbon::now()->formatLocalized('%d %B %Y') }}
        </div>

    </div>
</header>

resources/views/layouts/_sidebar.blade.php
<section class="main-sidebar">
    <div class="container">
        <div class="user_panel">
            <div class="row">
                <div class="col-sm-12">
                    <div class="info">
                        <label>{{ auth()->user()->full_name }}</label>
                        <label class="online"> <i class="fa fa-circle text-success"></i> online </label>
                    </div>
                </div>
            </div>
        </div>
        <!-- Start Navigation -->
        <ul class="sidebar-menu tree">
            <li class="header">Navigation</li>

            <li>
                <a href="{{ route('home') }}" class="btn bg-gray   text-left">
                    <i class="fa fa-home"></i> <span>Accueil</span>
                </a>
            </li>
            @if(auth()->user()->is_admin)
                <li>
                    <a href="{{ route('staff.index') }}" class="btn bg-gray text-left">
                        <i class="fa fa-users"></i> <span>Utilisateurs</span>
                    </a>
                </li>
            @endif
        </ul>
    </div>
</section>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="icon" type="image/png" href="{{ asset('/images/logo-gaz.png') }}" />
    <link rel="apple-touch-icon" type="image/png" href="{{ asset('/images/logo-gaz.png') }}" />
    <!-- app.js -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/datatable.min.css') }}">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- bootstrap -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap/bootstrap.css') }}">

</head>
<body >
<div class="adm">

    @include('layouts._navbar')
    @include('layouts._sidebar')

    <main class="py-4 content_section" id="my-app" >
        @include('layouts._flash')
        @yield('content')
    </main>


</div>

<!-- jqeury -->
<script src="{{ asset('js/jquery/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/jquery/popper.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/bootstrap/bootstrap.min.js') }}"  type="text/javascript"></script>
<script src="{{ asset('js/datatable.min.js') }}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="{{ asset('js/main_o.js') }}"></script>
<script src="{{ asset('js/app.js') }}" defer></script>
@stack('scripts')
</body>
</html>

resources/views/layouts/app_guest.blade.php
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="icon" type="image/png" href="{{ asset('/images/logo-gaz.png') }}" />
    <link rel="apple-touch-icon" type="image/png" href="{{ asset('/images/logo-gaz.png') }}" />
    <!-- bootstrap -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap/bootstrap.css') }}">
    <!-- app.js -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/datatable.min.css') }}">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
<div class="container">
    @yield('content')
</div>

</body>
</html>